on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - shell: bash
        run: "for i in spacetime warmongr; do ./latest.sh $i; done;"
      - shell: bash
        run: ./init.sh
      - shell: bash
        run: "for i in spacetime warmongr; do ./screenshot.sh $i-latest.apk; done;"
      #- uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 31
      #    arch: x86_64
      #    script: "for i in spacetime warmongr; do ./screenshot.sh $i-latest.apk; done;"
      #- if: ${{ always() }}
      #  uses: actions/upload-artifact@v3
      #  with:
      #    path: screenshot*.png
      - if: ${{ always() }}
        shell: bash
        run: |
          git config user.name sirekanian
          git config user.email sirekanian@pm.me
          git add spacetime warmongr
          git commit -m updated || true
          git push
